### ISSUE TITLE
Failed to extend & union mbtiles

### ISSUE THREAD

**Issue by predictwise** [consbio/pymbtiles#4]
Hi,

I am using function `extend` in `ops.py` to merge two different raster mbtiles.

The size of target mbtiles does increase after extending. However, when I list available tiles in the target mbtiles, I find out the tiles of source mbtiles hadn't been added into target mbtiles. 

The same situation also occurs during the `union` operation. I have no idea why this could happen.

Oliver

**Comment by brendan-ward** [comment]
@predictwise how are you listing the tiles available in the target after `extend` and `union`?

For `extend`, the only thing that it checks is if the tile [already exists](https://github.com/consbio/pymbtiles/blob/master/pymbtiles/ops.py#L29).  Likewise, that is also used at the core of `union`.

It would be good to inspect the source and target manually to make sure there are tiles not present in the target that are present in the source.  Then, using a SQLite viewer, view the contents after `extend` or `union` and see if that tile is now present.

If not, then it would be helpful if you could share a small source and target mbtiles file that reproduce this issue for our testing.

**Comment by predictwise** [comment]
Hi @brendan-ward 

Sorry for replying late. I found out the function `extend` inserts data into two new tables `images` and `map` instead of table `tiles`. Why did you do that? Because if I release the mbtiles as a tile server using [mbtiles-server](https://github.com/DenisCarriere/mbtiles-server#readme), it will request tiles from table `tiles` by default and will not request tiles from table `map` and `images`.

I think the best solution is to directly insert data into table `tiles`.

Oliver

**Comment by brendan-ward** [comment]
@predictwise I modeled the data structure in the sqlite file off other `mbtiles` implementations that use a `tiles` view and `map` and `images` to store the actual data.  While a bit less direct than storing all tiles in `tiles`, it allows us to de-duplicate tile data (multiple entries in `map` point to same entry in `images`).

My oversight here was that I didn't consider tilesets created using other tools that only use `tiles`; we don't create a `tiles` view if one doesn't exist, but we always insert into `map` and `images`.  

I definitely do not want to drop our primary use of `tiles` as a view, but I'd be willing to consider generalizing these functions and the tile writer functions to handle `tiles` table vs `tiles` view supported by `images` and `map`.

**Comment by predictwise** [comment]
Hi @brendan-ward 

Thanks for your great work and it really helps me a lot. I modified some your codes to satisfy my requirements. I think I can close this issue now.

Oliver
